#!/bin/bash

cd ..
npm init -y
npm install -D tailwindcss
npx tailwindcss init
cp php-tail/files/tailwind.config.js .
mkdir src
cp php-tail/files/input.css src/
sed -i '2i"scripts": {\
  "dev": "npx tailwindcss -i ./src/input.css -o ./src/output.css --watch"\
},' package.json
rm -rf php-tail
echo "DO NOT FORGET TO ADD output.css IN YOUR PHP FILE!"
